Добавляет разметку главной страницы
zvovasteach/daniil-device-html1 pull request #2
Opened 2022-09-05 17:31 UTC by dvovas

2022-09-05 19:09 UTC, evovas requested changes
Для первого раза очень даже неплохо. Продолжай)

2022-09-05 19:09 UTC, evovas commented on index.html
> +    <button class="button button-search-main" type="submit"> Найти</button>
Класс button здесь лишний, так как эта кнопка не стандартная (закругленные границы) и используется только тут.

2022-09-05 19:09 UTC, evovas commented on index.html
> +    <button class="button button-search-main" type="submit"> Найти</button>
Так же пробелы после тега нельзя использовать.

2022-09-05 19:09 UTC, evovas commented on index.html
> +  <section class="first">
Класс никак не должен рассказывать о том, что конкретно лежит внутри тега. Так же first это слишком общее понятие, которое может относиться к чему угодно на странице. Нужно поменять название класса. Посмотри на все классы в коде, и исправь их в соответствии с этим комментарием.

2022-09-05 19:09 UTC, evovas commented on index.html
> +    <img class="slider-image" src="">
Стрелочки это не контентное изображение, ценности для пользователя они не представляют. Сами стрелочки в дальнейшем будут фоном кнопок.

2022-09-05 19:09 UTC, evovas commented on index.html
> +      <span class="visually-hidden"> редыдущий товар</span>
Опечатка + пробел

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <p class="first-description">Этот обычный, на первый взгляд, квадрокоптер оснащен мощным лазером,
Перенос строк использовать нельзя

2022-09-05 19:09 UTC, evovas commented on index.html
> +        </div>
Вынести после списка

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <input class="item-number-get" type="radio" name="item-number">
Лишнее

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <span class="info-about-text">Радиус поражения</span>
Тег `b` используется внутри какого-то другого тега, только что бы выделить текст жирным, например внутри параграфа. Погугли использование тега `dl` и как его использовать.

2022-09-05 19:09 UTC, evovas commented on index.html
> +
Пусты строки здесь не нужны. Их делают между большими блоками типа `section` и всяких `header`, `main`, `footer`

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <h3 class="promo-heading">Худеем правильно!</h3>
Класс promo-heading звучит как заголовок всего списка, если используешь promo-item, то тогда используй класс promo-item-heading. И так для каждого тега элемента списка.

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <p class="first-description">Мотивирующие фитнес-браслеты помогут найти в себе силы не пропускать занятия и соблюдать диету.</p>
Здесь опять же как и писал в комментарии выше, ты используешь класс, который означает по сути "описание первого товара", но у тебя все описания товаров одинаковые, меняется только текст, поэтому нужно использовать класс который будет просто говорить promo-item-description

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <a class="about-item" href="#">Подробнее</a>
Если посмотришь в стайлгайд, то там у тебя три вида кнопок которые используются во многих местах проекта, это кнопка, точнее ссылка которая выглядит как кнопка, и при стилизации не имеет разницы какой тег ты будешь стилизовать, главное что он выглядит тем или иным образом.

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <h3 class="promo-heading">Делай селфи, как Бен Стиллер! </h3>
Изображение промотовара является контентным изображением, поэтому должно присутствовать в разметке. Так как это изображение конкретного слайда промо, то оно должно быть в каждом элементе списка. Лучше его вставить сразу после тега `h3`.

2022-09-05 19:09 UTC, evovas commented on index.html
> +    <h2 class="visually-hidden">Список разновидностей товаров</h2>
В заголовке лучше использовать _Категории товаров_

2022-09-05 19:09 UTC, evovas commented on index.html
> +        <a class="category-link" href="#">Моноподы для селфи</a>
Эта ссылка у тебя будет вести на страницу каталога, которую разметишь позже

2022-09-05 19:09 UTC, evovas commented on index.html
> +  </section>
Вот как раз после закрывающегося тега `section` можно добавить пустую строку.

2022-09-05 19:09 UTC, evovas commented on index.html
> +  <section class="services">
И так. У тебя здесь должно быть два списка:
1. Список кнопок с классом например services-controls. Он будет первым в разметке.
2. Список с текстами каждого сервиса (они есть в стайлгайде) с классом например services-list. Что должно быть в каждом элементе списка, попробуй решить сам.

2022-09-05 19:09 UTC, evovas commented on index.html
> +  <div class="item-delivery">Доставим редкий товар под заказ</div>
Если есть кнопка _Посмотреть дополнительную информацию_, то это относится к одному элементу. Значит их нужно добавить в общий `div`. А текст _Доставим редкий товар под заказ_ заключить в `p`.

Слово item используется только для классов элементов списка. product-on-order например можно.

2022-09-05 19:09 UTC, evovas commented on index.html
> +  <section class="contacts">
_О нас_ и _Контакты_ это два разных раздела у которых есть явные заголовки на макете.

2022-09-05 19:09 UTC, evovas commented on index.html
> +      <li class="service-navigation-item">
Напишу здесь, в чем есть проблема, посмотри по всему коду:
Ты делаешь список, а в списке один элемент. Есть два вопроса. Нужен ли тогда такой список? И если да, то что с этим списком не так?

2022-09-05 19:09 UTC, evovas commented on index.html
> +    </ul>
Посмотри, что здесь должно быть с писках, а чему хватит простого оборачивания в подходящий смысловой тег.

2022-09-05 19:09 UTC, evovas commented on index.html
> +  <section class="mailing-list">
Слово list используется только к классах для `ul` и `ol`

2022-09-05 19:09 UTC, evovas commented on index.html
> +    <h3 class="mailing-list-heading">Подпишитесь на рассылку</h3>
Заголовок это по сути название смыслового блока. У одного блока не может быть два названия.

2022-09-05 19:09 UTC, evovas commented on index.html
> +  <section class="footer-contacts">
В футере редко используются теги section потому, что в них обычно разрозненная информация сразу о многом. Так что тут будут просто отдельные теги, отдельные из которых будут обернуты в div'ы. Пересмотри как исправить во всем футере.

2022-09-05 19:09 UTC, evovas commented on index.html
> +<footer class="page-footer">
Логотип лучше вставить в самом начале футера.

2022-09-05 19:09 UTC, evovas commented on index.html
> +  </section>
В конце футера логотип академии, он тоже контетный.

2022-09-05 19:36 UTC, dvovas commented on index.html
> +        <a class="category-link" href="#">Моноподы для селфи</a>
Какая ссылка и о чем речь

2022-09-05 20:11 UTC, dvovas commented on index.html
> +    </ul>
Не сразу понятно что в какой тег надо описывать и как лучше их сгруппировать

2022-09-07 14:32 UTC, evovas requested changes

2022-09-07 14:32 UTC, evovas commented on index.html
> +    <button class="button-search-main" type="submit">https://www.figma.com/file/f8ZtnZcdWC2pSklG1ssm9K/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81-%2F-33?node-id=0%3A1Найти</button>
Это что за ссылка такая на кнопке?

2022-09-07 14:32 UTC, evovas commented on index.html
>      <input type="text" id="search-main" name="search-main" placeholder="Текст поиска">
Пропущен label для инпута

2022-09-07 14:32 UTC, evovas commented on index.html
> +      <button class="slider-control" type="button" active><span class="visually-hidden">Слайдер кнопка</span></button>
У кнопок не бывает атрибута active

2022-09-07 14:32 UTC, evovas commented on index.html
>        <input type="text" id="mailing-email" name="mailing-email-main" placeholder="Ваш e-mail">
Пропущен label для инпута
main тоже лишнее, вообще в name хватит простого email

2022-09-07 14:32 UTC, evovas commented on index.html
>      <address class="footer-contacts-address>"
Опечатка в коде. А так же тег `address` не закрыт

2022-09-07 14:32 UTC, evovas commented on index.html
> +      <li class="promo-item-heading">
heading переводится как "заголовок", я имел ввиду что такой класс нужно задать заголовку
_promo-list, promo-item, promo-description_ так правильно

2022-09-07 14:32 UTC, evovas commented on index.html
> +          <dt class="info-about-main">Радиус поражени</dt>
Именно поэтому я говорю тебе, что нужно научиться быстро копировать текст из фигмы, а не набирать его руками, даже если это тебе кажется быстрее, потому что так ты совершаешь опечатки. Если приноровиться копировать текст из фигмы, то это делается в считанные секунды. И это важно, потому что на реальных макетах мелкого текста может быть до невозможности много и такие опечатки потом фиг найдешь. А если будет опечатка с фигмы, то всегда можно сказать, что копировал с макета, не заметил и исправить фразу/слово.

2022-09-07 14:32 UTC, evovas commented on index.html
> +  <img class="heade-logo" src="" alt="Логотип магазина device">
Пробегайся по коду глазами и смотри подчеркивания все. Много опечаток. Указываю на эту, другие еще есть.

2022-09-07 14:32 UTC, evovas commented on index.html
> +        <img class="slider-image" src="" alt="Фотография квадрокоптера">
У тебя изображение находится в блоке promo, класс здесь лучше будет promo-image, потому что весь контент здесь является слайдером

2022-09-07 14:32 UTC, evovas commented on index.html
> +        <a class="button-yellow about-item" href="#">Подробнее</a>
Опять же класс должен быть связан с блоком где он находится. Рассуждай примерно так:
Что это такое? Ссылка. Где она находится? В блоке промо. Есть еще ссылки в этом блоке с которыми может быть конфликтовать класс? Нет. 
Значит класс будет правильный promo-link (вместо about-item). Посмотри на остальные классы в слайдах промо и исправь с учетом этого комментария.

2022-09-07 14:32 UTC, evovas commented on index.html
> +          <dd class="info-about-sup">8,5 м</dd>
Тут несколько комментариев. Во первых как раз тут нужно посмотреть на комментарий выше. Но сейчас поговорим о словах на конце класса. Хорошо, что для каждого элемента одинакового ты используешь одинаковые классы. 
Но но давай расшифруем сокращения тегов: dl (Description List), dt (Description Term), dd (Description Description). И вот эти окончания лучше и ставить в конце класса. Вместо main - term, вместо sup - description. 
А еще я не понял что вообще значит sup. Если это сокращение, то сокращения запрещены кроме тех, которые понятны всем разработчикам например image - img и т.д.

2022-09-07 14:32 UTC, evovas commented on index.html
> +          <dd class="info-about-sup">Материал</dd>
Перепутаны местами термин и описание

2022-09-07 14:32 UTC, evovas commented on index.html
> +      <button class="slider-control" type="button"><span class="visually-hidden">Слайдер кнопка</span></button>
В спанах лучше будет указать Слайд 1, Слайд 2 и т.д. Потому что так понятнее что кнопка делает, а еще это легче будет в дальнейшем при добавлении JS, с автоматическим проставлением номеров.

2022-09-07 14:32 UTC, evovas commented on index.html
> +  <section class="products-catalog">
Опять же лучше придерживаться единого стиля в названиях классов внутри секции. 
categories, categories-list, categories-link

2022-09-07 14:32 UTC, evovas commented on index.html
>      </ul>
Еще раз прошу, что бы ты внимательно просматривал код перед отправкой на проверку с учетом прошлых комментариев. У тебя опять список из одного элемента. Внимательно. Задавая сам себе вопросы о каждом участке кода.

2022-09-07 14:32 UTC, evovas commented on index.html
> +        <button class="button-yellow services-navigation-button" type="button">Доставка</button></li>
Если у тебя тег открывается на одной строчке, а содержимое идет с новой строки, то тег обязательно должен закрываться на новой строчке:
```
<li class="services-controls-item">
  <button class="button-yellow services-navigation-button" type="button">Доставка</button>
</li>
```
Если содержимое тега находится на той же строке, где открывается тег, то переносы не нужны.

2022-09-07 14:32 UTC, evovas commented on index.html
> +        <h3 class="services-heading">Доставка</h3>
Опять же вот у тебя блок services-info, значит services-heading лучше заменить на services-info-heading и т.д.

2022-09-07 14:32 UTC, evovas commented on index.html
> +  <section class="about-us-main">
Отступы

2022-09-07 14:32 UTC, evovas commented on index.html
> +  </section>
about-us-main - слово main лишнее
Далее отступы
И посмотри комментарий про то как именовать классы и попробуй исправить все классы на правильные.

2022-09-07 14:32 UTC, evovas commented on index.html
>    </section>
То же самое что и в комментарии выше. Все 3 пункта.

2022-09-07 14:32 UTC, evovas commented on index.html
> +  <section class="mailing">
Вместо mailing лучше subscription

2022-09-07 14:32 UTC, evovas commented on index.html
> +    <p class="mailing-heading-text">Еженедельный дайджест с обзорами новинок, длительными тест-драйвами, распаковками, а также акции, спецпредложения и вот это вот всё.</p>
Опять же heading используется только в заголовках. И если ты везде вместо слова text используешь description то продолжай его использовать везде.

2022-09-07 14:32 UTC, evovas commented on index.html
> +      <button class="button button-mailing-email" type="submit">Подписаться</button>
Подумай как исправить класс. Можно все обсудить вообще уже в устном формате.

2022-09-07 14:32 UTC, evovas commented on index.html
>      <p class="about-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
Тег `p` лишний, если используешь `address`

2022-09-07 14:32 UTC, evovas commented on index.html
>  <footer class="page-footer">
Проверь отступы во всем футере
А так же названия классов нужно подумать как исправить. Можем это обсудить и вместе решить как назвать их правильно.

2022-09-07 15:02 UTC, dvovas commented on index.html
>      <input type="text" id="search-main" name="search-main" placeholder="Текст поиска">
Зачем здесь label если это поле для ввода текста и по сути здесь лишний только атрибут for

2022-09-07 15:03 UTC, dvovas commented on index.html
> +      <button class="slider-control" type="button" active><span class="visually-hidden">Слайдер кнопка</span></button>
У кнопки вообще не бывает свойства активности как я понял, и функцию показа аткивной кнопки (выбранного изображения) будет задаваться в css?

2022-09-07 15:04 UTC, dvovas commented on index.html
>        <input type="text" id="mailing-email" name="mailing-email-main" placeholder="Ваш e-mail">
Здесь как я понимаю тоже атрибут id лишний

2022-09-07 15:09 UTC, dvovas commented on index.html
>      <address class="footer-contacts-address>"
Не вижу опечатки

2022-09-07 15:26 UTC, dvovas commented on index.html
>      </ul>
Удалил список

2022-09-07 15:36 UTC, dvovas commented on index.html
> +    <p class="mailing-heading-text">Еженедельный дайджест с обзорами новинок, длительными тест-драйвами, распаковками, а также акции, спецпредложения и вот это вот всё.</p>
Под вопросом, как тогда переименовать класс <span class="subscription-text-description">Это бесплатно</span>
и   <p class="about-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>

2022-09-07 15:37 UTC, dvovas commented on index.html
> +      <button class="button button-mailing-email" type="submit">Подписаться</button>
Обсудим

2022-09-07 18:44 UTC, evovas approved these changes
Поправь по комментариям к следующему пулреквесту

2022-09-07 18:44 UTC, evovas commented on index.html
> +    <p class="product-on-order">Доставим редкий товар под заказ</p>
Вот здесь поправь в следующем пулреквесте со страницей каталога

2022-09-07 18:44 UTC, evovas commented on index.html
> +  <img class="header-logo" src="" alt="Логотип магазина device">
Кстати вот здесь забыл. Логотип является ссылкой, которая всегда ведет на главную. Посмотри как в академии с ним поступают, на главной странице есть свои нюансы у этой ссылки.

2022-09-07 18:44 UTC, evovas commented on index.html
> +    <button class="product-info" type="button">
И здесь

2022-09-07 18:44 UTC, evovas commented on index.html
> +      <a class="contacts-phone" href="tel:+78128121212">+7 (812) 812-12-12</a>
Отступ

2022-09-07 18:44 UTC, evovas commented on index.html
> +    <p class="subscription-description">Еженедельный дайджест с обзорами новинок, длительными тест-драйвами, распаковками, а также акции, спецпредложения и вот это вот всё.</p>
Переноси строки в таких длинных кусках текста

2022-09-07 18:45 UTC, merged